package model;

import lombok.Data;

/**
 * Represents a vehicle with a manufacturer, model name, and current speed.
 * Getters, setters, {@code equals}, {@code hashCode}, and {@code toString} are
 * generated by Lombok {@code @Data}.
 *
 * @author Daniel Appenmaier
 * @version 1.0
 */
@Data
public class Vehicle {

   /** The manufacturer of the vehicle (e.g., {@code "Skoda"}). */
   private final String make;

   /** The model name of the vehicle (e.g., {@code "Superb Combi"}). */
   private final String model;

   /** The current speed of the vehicle in kilometres per hour. */
   private double speedInKmh;

}
